//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\DanieleFrancioni\OneDrive - Binarydea\Code\Sincronica\powershell-bicep-converter\src\BicepGrammar\bicepParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="bicepParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IbicepParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.bicep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBicep([NotNull] bicepParser.BicepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] bicepParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput([NotNull] bicepParser.OutputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.targetScope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTargetScope([NotNull] bicepParser.TargetScopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScope([NotNull] bicepParser.ScopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] bicepParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.decorator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecorator([NotNull] bicepParser.DecoratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] bicepParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] bicepParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource([NotNull] bicepParser.ResourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.resourceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourceType([NotNull] bicepParser.ResourceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.modulePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModulePath([NotNull] bicepParser.ModulePathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] bicepParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.valueExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExpression([NotNull] bicepParser.ValueExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.memberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberExpression([NotNull] bicepParser.MemberExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember([NotNull] bicepParser.MemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReference([NotNull] bicepParser.ReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] bicepParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.functionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionParameter([NotNull] bicepParser.FunctionParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.stringValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringValue([NotNull] bicepParser.StringValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.boolValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolValue([NotNull] bicepParser.BoolValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.numberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberValue([NotNull] bicepParser.NumberValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.arrayValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayValue([NotNull] bicepParser.ArrayValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.objectValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectValue([NotNull] bicepParser.ObjectValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty([NotNull] bicepParser.PropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="bicepParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyName([NotNull] bicepParser.PropertyNameContext context);
}
