//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\DanieleFrancioni\OneDrive - Binarydea\Code\Sincronica\powershell-bicep-converter\src\BicepGrammar\bicepParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IbicepParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class bicepParserBaseListener : IbicepParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.bicep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBicep([NotNull] bicepParser.BicepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.bicep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBicep([NotNull] bicepParser.BicepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule([NotNull] bicepParser.ModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule([NotNull] bicepParser.ModuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput([NotNull] bicepParser.OutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput([NotNull] bicepParser.OutputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.targetScope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTargetScope([NotNull] bicepParser.TargetScopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.targetScope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTargetScope([NotNull] bicepParser.TargetScopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScope([NotNull] bicepParser.ScopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScope([NotNull] bicepParser.ScopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] bicepParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] bicepParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.decorator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecorator([NotNull] bicepParser.DecoratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.decorator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecorator([NotNull] bicepParser.DecoratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] bicepParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] bicepParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] bicepParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] bicepParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResource([NotNull] bicepParser.ResourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResource([NotNull] bicepParser.ResourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.resourceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResourceType([NotNull] bicepParser.ResourceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.resourceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResourceType([NotNull] bicepParser.ResourceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.modulePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModulePath([NotNull] bicepParser.ModulePathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.modulePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModulePath([NotNull] bicepParser.ModulePathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] bicepParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] bicepParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.valueExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueExpression([NotNull] bicepParser.ValueExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.valueExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueExpression([NotNull] bicepParser.ValueExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.memberExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberExpression([NotNull] bicepParser.MemberExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.memberExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberExpression([NotNull] bicepParser.MemberExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember([NotNull] bicepParser.MemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember([NotNull] bicepParser.MemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReference([NotNull] bicepParser.ReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReference([NotNull] bicepParser.ReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] bicepParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] bicepParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.functionParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionParameter([NotNull] bicepParser.FunctionParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.functionParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionParameter([NotNull] bicepParser.FunctionParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.stringValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringValue([NotNull] bicepParser.StringValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.stringValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringValue([NotNull] bicepParser.StringValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.boolValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolValue([NotNull] bicepParser.BoolValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.boolValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolValue([NotNull] bicepParser.BoolValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.numberValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberValue([NotNull] bicepParser.NumberValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.numberValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberValue([NotNull] bicepParser.NumberValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.arrayValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayValue([NotNull] bicepParser.ArrayValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.arrayValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayValue([NotNull] bicepParser.ArrayValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.objectValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectValue([NotNull] bicepParser.ObjectValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.objectValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectValue([NotNull] bicepParser.ObjectValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] bicepParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] bicepParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyName([NotNull] bicepParser.PropertyNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyName([NotNull] bicepParser.PropertyNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
