//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\DanieleFrancioni\OneDrive - Binarydea\Code\Sincronica\powershell-bicep-converter\src\BicepGrammar\bicepParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="bicepParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IbicepParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.bicep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBicep([NotNull] bicepParser.BicepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.bicep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBicep([NotNull] bicepParser.BicepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] bicepParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] bicepParser.ModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput([NotNull] bicepParser.OutputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput([NotNull] bicepParser.OutputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.targetScope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTargetScope([NotNull] bicepParser.TargetScopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.targetScope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTargetScope([NotNull] bicepParser.TargetScopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScope([NotNull] bicepParser.ScopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScope([NotNull] bicepParser.ScopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] bicepParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] bicepParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.decorator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecorator([NotNull] bicepParser.DecoratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.decorator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecorator([NotNull] bicepParser.DecoratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] bicepParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] bicepParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] bicepParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] bicepParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResource([NotNull] bicepParser.ResourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResource([NotNull] bicepParser.ResourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.resourceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResourceType([NotNull] bicepParser.ResourceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.resourceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResourceType([NotNull] bicepParser.ResourceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.modulePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModulePath([NotNull] bicepParser.ModulePathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.modulePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModulePath([NotNull] bicepParser.ModulePathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] bicepParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] bicepParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.valueExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueExpression([NotNull] bicepParser.ValueExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.valueExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueExpression([NotNull] bicepParser.ValueExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.memberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberExpression([NotNull] bicepParser.MemberExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.memberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberExpression([NotNull] bicepParser.MemberExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember([NotNull] bicepParser.MemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember([NotNull] bicepParser.MemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReference([NotNull] bicepParser.ReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReference([NotNull] bicepParser.ReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] bicepParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] bicepParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.functionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionParameter([NotNull] bicepParser.FunctionParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.functionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionParameter([NotNull] bicepParser.FunctionParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.stringValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringValue([NotNull] bicepParser.StringValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.stringValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringValue([NotNull] bicepParser.StringValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.boolValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolValue([NotNull] bicepParser.BoolValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.boolValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolValue([NotNull] bicepParser.BoolValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.numberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberValue([NotNull] bicepParser.NumberValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.numberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberValue([NotNull] bicepParser.NumberValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.arrayValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayValue([NotNull] bicepParser.ArrayValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.arrayValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayValue([NotNull] bicepParser.ArrayValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.objectValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectValue([NotNull] bicepParser.ObjectValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.objectValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectValue([NotNull] bicepParser.ObjectValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty([NotNull] bicepParser.PropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty([NotNull] bicepParser.PropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bicepParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyName([NotNull] bicepParser.PropertyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bicepParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyName([NotNull] bicepParser.PropertyNameContext context);
}
