name: Build module
on:
  push:
    tags:        
      - '[0-9]+\.[0-9]+\.[0-9]'
jobs:
  buildModule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse output tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build the module
        shell: pwsh
        run: |
          ./build.ps1 -version '${{ steps.vars.outputs.tag }}'
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          prerelease: true
          name: ${{ steps.vars.outputs.tag }}
          token: ${{ github.token }}
          files: |
            ./output/PSBicepParser/*
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: ${{ github.token }}
#          automatic_release_tag: ${{ steps.vars.outputs.tag }}
#          prerelease: true
#          title: ${{ steps.vars.outputs.tag }}

#      - name: Publish in PowershellGallery
#        shell: pwsh
#        run: |
#          Publish-Module -path ./output/PSBicepParser -NuGetApiKey '${{ secrets.PSGALLERYAPIKEY }}' -Verbose 
