name: GitHub Actions Demo
on:
  push:
    tags:        
      - '[0-9]+\.[0-9]+\.[0-9]'
jobs:
  buildModule:
    runs-on: ubuntu-latest
    steps:
      - name: Build the module
        shell: pwsh
        run: |
          ./build.ps1 -version '${GITHUB_REF##*/}'
