name: Build module
on:
  push:
    tags:        
      - '[0-9]+\.[0-9]+\.[0-9]'
jobs:
  buildModule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse output tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build the module
        shell: pwsh
        run: |
          ./build.ps1 -version '${{ steps.vars.outputs.tag }}'
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: ${{ steps.vars.outputs.tag }}
          prerelease: true
          title: ${{ steps.vars.outputs.tag }}
          body: |
            Automatic release
          files: |
            ./output/PSBicepParser/*
#      - name: Publish in PowershellGallery
#        shell: pwsh
#        run: |
#          Publish-Module -path ./output/PSBicepParser -NuGetApiKey '${{ secrets.PSGALLERYAPIKEY }}' -Verbose 
