name: Build module
on:
  push:
    tags:        
      - '[0-9]+\.[0-9]+\.[0-9]'
jobs:
  buildModule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse output tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build the module
        shell: pwsh
        run: |
          ./build.ps1 -version '${{ steps.vars.outputs.tag }}'
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ steps.vars.outputs.tag }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Publish in PowershellGallery
        shell: pwsh
        run: |
          Publish-Module -path ./output/PSBicepParser -NuGetApiKey '${{ secrets.PSGALLERYAPIKEY }}' -Verbose 
